---
title: "pnas"
author: "zhong"
date: "2018年10月13日"
output: pdf_document
---


##Load and install the required packages.

```{r, echo=TRUE,results='hide', message=FALSE, warning=FALSE}
library("ChIPseeker")
library("org.Mm.eg.db")
library("TxDb.Mmusculus.UCSC.mm10.knownGene")
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
library("clusterProfiler")
library("ReactomePA")
library("DOSE")
library(dplyr)
library(ggplot2)
```

```{r, echo=TRUE,warning=FALSE}
library(magrittr) # for R's pipe operator %>%
# theme for ggplot2
theme_set(theme_bw())
pal = "Set1"
scale_colour_discrete <- function(palname = pal, ...) {
  scale_colour_brewer(palette = palname, ...)
}
scale_fill_discrete <- function(palname = pal, ...) {
  scale_fill_brewer(palette = palname, ...)
}
set.seed(2016)
main_theme = theme(panel.background=element_blank(),
                    panel.grid=element_blank(),
                    axis.line.x=element_line(size=.5, colour="black"),
                    axis.line.y=element_line(size=.5, colour="black"),
                    axis.ticks=element_line(color="black"),
                    axis.text=element_text(color="black", size=7),
                    legend.position="right",
                    legend.background=element_blank(),
                    legend.key=element_blank(),
                    legend.text= element_text(size=7),
                    text=element_text(family="sans", size=7))
```


```{r, echo=FALSE}
setwd("/home/zhong/mac")
ring1B <- readPeakFile("ring1B/ring1B_summits.bed")
suz=readPeakFile("suz/suz_summits.bed")



#ChIP peaks coverage plot
#Showing the peak locations over the whole genome
covplot(peak, weightCol="V5")
#Heatmap of ChIP binding to TSS regions
promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
tagMatrix <- getTagMatrix(ring1B, windows=promoter)
tagHeatmap(tagMatrix, xlim=c(-3000, 3000), color="red")

#Average Profile of ChIP peaks binding to TSS region
plotAvgProf(tagMatrix, xlim=c(-3000, 3000), resample = 1000)

ringb1_peakAnno<-annotatePeak(ring1B,tssRegion = c(-2500, 2500), TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene, annoDb="org.Mm.eg.db")
suz12_peakAnno=annotatePeak(suz,tssRegion = c(-2500, 2500), TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene, annoDb="org.Mm.eg.db")
suz12_peakAnno<-annotatePeak(suz,tssRegion = c(-2500, 2500), TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene, annoDb="org.Mm.eg.db")


peaks <-list(ring1B=ring1B,suz=suz)
peakAnnoList <- lapply(peaks, annotatePeak, tssRegion=c(-2500,2500), TxDb=txdb, 
                       addFlankGeneInfo=TRUE, flankDistance=5000)
names(peakAnnoList)=c("ring1B","suz")
plotDistToTSS(peakAnnoList)
#可视化 Pie and Bar plot
plotAnnoBar(peakAnnoList)
vennpie(peakAnnoList[[1]])
upsetplot(peakAnnoList[[1]])
plotAnnoPie(peakAnnoList[[1]])


#多个peak的比较

promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
tagMatrixList <- lapply(peaks, getTagMatrix, windows=promoter)
plotAvgProf(tagMatrixList, xlim=c(-3000, 3000))
plotAvgProf(tagMatrixList, xlim=c(-3000, 3000),resample=500, facet="row")
tagHeatmap(tagMatrixList, xlim=c(-3000, 3000), color=NULL)


over_lap<-findOverlapsOfPeaks(1,2,3,4)
png('overlapVenn.png')
makeVennDiagram(over_lap)
dev.off()


genes= lapply(peakAnnoList, function(i) as.data.frame(i)$geneId)
#venn.diagram(genes, imagetype = "png", fill = c("blue", "green"), alpha = c(0.5, 0.5)  ,filename = "venn.png")


#Functional enrichment analysis
# Multiple samples KEGG analysis
compKEGG <- compareCluster(geneCluster = gene, 
                         fun = "enrichKEGG",
                         organism = "mouse",
                         pvalueCutoff  = 0.05, 
                         pAdjustMethod = "BH")
dotplot(compKEGG, showCategory = 20, title = "KEGG Pathway Enrichment Analysis")







#样本共有的靶基因在TSS附近的profile图
common_gene <- Reduce(intersect,genes)
#fourgenes <- intersect(genes[[1]],intersect(genes[[2]],intersect(genes[[3]],genes[[4]])))
ring1B=as.data.frame(ring1B_peakAnno)$geneId
suz12=as.data.frame(suz12_peakAnno)$geneId
ring1B_df <- as.data.frame(ring1B_peakAnno) 
ring1B_peak <- GRanges(ring1B_df[ring1B_df$geneId %in% common_gene, 1:12])
suz12_df <- as.data.frame(suz12_peakAnno)
suz12_peak <- GRanges(suz12_df[suz12_df$geneId %in% common_gene, 1:12])
list_peak <- list(ring1B=ring1B_peak, suz12=suz12_peak) 



tagMatrixList <- lapply(list_peak, getTagMatrix, window=promoter)
plotAvgProf(tagMatrixList , xlim = c(-3000,3000))


upset(fromList(genes))

```

```{r, echo=TRUE}


```

```{r, echo=TRUE}


```


```{r, echo=TRUE}


```


